name: cache_nexus_example
description: Example Flutter app demonstrating cache_nexus with Dio
publish_to: 'none'

environment:
  sdk: ^3.11.5
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  cache_nexus:
    path: ../
  dio: ^5.4.0
  hive_flutter: ^1.1.0
  connectivity_plus: ^7.1.1
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  lints: ^6.0.0

flutter:
  uses-material-design: true
